### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lio/resourcepool/ssdp/client/SsdpClient

### ISSUE THREAD

**Issue by giripradip** [resourcepool/ssdp-client#10]
I have added this project via gradle.  And implemented the discover services task. But I got this java runtime error java.lang.NoClassDefFoundError: Failed resolution of: Lio/resourcepool/ssdp/client/SsdpClient. How to solve this problem? I even tried to clean the project, uninstall the old app and re-run it again still could not solve the problem. Thanks!

**Comment by loicortola** [comment]
Hello @giripradip mmmh, can you send me your gradle file?

**Comment by loicortola** [comment]
Closed for inactivity
