### ISSUE TITLE
Can not receive notify msg

### ISSUE THREAD

**Issue by smarkm** [resourcepool/ssdp-client#12]
I can I receive the search msg, but for NOTIFY msg I can get it in Wireshark but not in the client.

**Comment by loicortola** [comment]
Hello @smarkm ,
sure. The client was designed to also support NOTIFY Msgs...
Do you have a NOTIFY msg sample I could work with?
I found some samples and tests are good!

**Comment by FabianKnapp** [comment]
This ticket should not be closed yet:

ResponseParser, line 28:
`private static final Pattern SERVICE_ANNOUNCEMENT_LINE_PATTERN = Pattern.compile("NOTIFY \\* HTTP/1.1");`

Must be:
`private static final Pattern SERVICE_ANNOUNCEMENT_LINE_PATTERN = Pattern.compile("NOTIFY \\* HTTP/1\\.1");`

**Comment by loicortola** [comment]
Hello Fabian,

yes you are right. I am on vacation, I can merge your PR, can you make it ?

**Comment by FabianKnapp** [comment]
> Hello Fabian,
> 
> yes you are right. I am on vacation, I can merge your PR, can you make it ?

Sure. Have a good time!

**Comment by FabianKnapp** [comment]
#21 resolves this issue.
