### ISSUE TITLE
[Feature request] Custom interval between requests

### ISSUE THREAD

**Issue by luizgrp** [resourcepool/ssdp-client#13]
Hi @loicortola, thanks for this library.

Currently the interval between subsequent discovery requests is hardcoded [here](https://github.com/resourcepool/ssdp-client/blob/master/src/main/java/io/resourcepool/ssdp/client/impl/SsdpClientImpl.java#L36). It would be nice to allow it to be customised. 

I'm happy to submit a pull request, I just want to check first if you are happy in having this change and how would you prefer it done.

I would suggest to add an optional `intervalBetweenRequests` parameter to DiscoveryRequest class, so the intervals can be set per request.

Please let me know your thoughts.

**Comment by loicortola** [comment]
Hello @luizgrp ,

just added this to the API, will be released in 2.3.0

Sorry I am so late and thanks for taking the time to write the Issue :)
