### ISSUE TITLE
[Feature request] Custom header values for M-SEARCH request

### ISSUE THREAD

**Issue by luizgrp** [resourcepool/ssdp-client#14]
It would be nice if the headers of the M-SEARCH could be customised. Currently, MX and USER-AGENT headers are hardcoded [here](https://github.com/resourcepool/ssdp-client/blob/5c44131c159189e53dfed712bc10b8b3444776b6/src/main/java/io/resourcepool/ssdp/client/request/SsdpDiscovery.java#L22)

I'm happy to submit a pull request, I just want to check first if you are happy in having this change and how would you prefer it done.

I would suggest to add `mx` and `userAgent` parameters to DiscoveryRequest.

Then the Builder could validate their values according to the [spec](http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf):

|Header|Type|Required|Spec|
|--|--|--|--|
| MX | Integer | REQUIRED | Field value contains maximum wait time in seconds. MUST be greater than or equal to 1 and SHOULD be less than 5 inclusive. |
| USER-AGENT | String | OPTIONAL | Specified by UPnP vendor. Field value MUST begin with the following “product tokens” (defined by HTTP/1.1). The first product token identifies the operating system in the form OS name/OS version, the second token represents the UPnP version and MUST be UPnP/1.1, and the third token identifies the product using the form product name/product version.  |

We could also add validation for the ST header, as currently there is none.

Or we could have no validations at all to any field in order to allow the users to use bogus values at their will.

Please let me know your thoughts.

**Comment by loicortola** [comment]
Interesting, I moved it to a DiscoveryOptions class which will be able to specify custom header values.
