### ISSUE TITLE
not find devices

### ISSUE THREAD

**Issue by Nuclear6** [resourcepool/ssdp-client#16]
only find device for router, ip is 192.168.50.1, its the scan result :

Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8de::urn:schemas-upnp-org:device:WANConnectionDevice:1', serviceType='urn:schemas-upnp-org:device:WANConnectionDevice:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dc::urn:schemas-upnp-org:device:InternetGatewayDevice:1', serviceType='urn:schemas-upnp-org:device:InternetGatewayDevice:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dc::upnp:rootdevice', serviceType='upnp:rootdevice', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dd', serviceType='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dd', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dc', serviceType='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dc', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dc::urn:schemas-upnp-org:service:Layer3Forwarding:1', serviceType='urn:schemas-upnp-org:service:Layer3Forwarding:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8de::urn:schemas-upnp-org:service:WANPPPConnection:1', serviceType='urn:schemas-upnp-org:service:WANPPPConnection:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dd::urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1', serviceType='urn:schemas-upnp-org:service:WANCommonInterfaceConfig:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8de::urn:schemas-upnp-org:service:WANIPConnection:1', serviceType='urn:schemas-upnp-org:service:WANIPConnection:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8dd::urn:schemas-upnp-org:device:WANDevice:1', serviceType='urn:schemas-upnp-org:device:WANDevice:1', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}
Found service: SsdpService{serialNumber='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8de', serviceType='uuid:1b04e4d8-07c0-4a50-b37e-3040283ac8de', location='http://192.168.50.1:48261/rootDesc.xml', remoteIp=192.168.50.1}

who can help me ?

**Comment by Nuclear6** [comment]
add parameter of PORT when init Multicase object can resolve my problem. As shown below:
<img width="1058" alt="resolve" src="https://user-images.githubusercontent.com/49468241/68556493-7b9c2b00-046d-11ea-822d-1f0a18664482.png">

**Comment by loicortola** [comment]
Hello @BaiduSu ,
SSDP Multicast Port is standard and should not be changed...
You might have an issue with your interfaces, this will be fixed in 2.3.0 released today!
