### ISSUE TITLE
SsdpClient.create() should be static

### ISSUE THREAD

**Issue by DavidMCarek** [resourcepool/ssdp-client#2]
We are using this library for an Android app and came across the create() method inside the SsdpClient class. In the documentation the create() method is called in a static way. "SsdpClient.create()" The create method is currently non-static and cannot be called in the way the documentation specifies.

**Comment by loicortola** [comment]
Hello @DavidMCarek 
sorry I did not respond earlier.
Let me make the correction and release the new version.
Thanks :)

**Comment by loicortola** [comment]
@DavidMCarek ,
merged in 2.0.0.
Be careful, most packages have changed after refactoring (just have to reimport)
