### ISSUE TITLE
is it possible to parse xml of location?

### ISSUE THREAD

**Issue by theRemoter** [resourcepool/ssdp-client#24]
Hello

is there a way to fetch the data inside the location of the discovered device?
if I got the location for example: http://XXX.XXX.XX.XX:8008/ssdp/device-desc.xml

so can I get the xml of this document and parse it with this lib?

thanks

**Comment by loicortola** [comment]
Hello @theRemoter ,
this lib is not really an XML Parser.
If you want to parse XML files, you can simply use an HTTP Client to get the XML file, then use any XML parser in Java to do whatever you want.

The SSDP-client only allows you to discover the devices & services, what you do with it after is only up to you.

Best wishes,

Loïc
