### ISSUE TITLE
Not able to discover Hubitat Hub, but UPnP Browser on same device finds it instantly

### ISSUE THREAD

**Issue by jpage4500** [resourcepool/ssdp-client#25]
Hi @loicortola -- first off thanks for providing this library. 

I want to use it to auto-discover a Hubitat Hub in my Android app. I ran a test and found a bunch of devices but not the Hubitat Hub. I also ran a scan using [UPnP browser](https://play.google.com/store/apps/details?id=com.dgmltn.upnpbrowser&hl=en_US&gl=US) and it found my hub right away.

I've [confirmed](https://community.hubitat.com/t/how-to-discover-hub-using-upnp/58839/3?u=jpage4500) the Hubitat Hub uses SSDP so the only thing I can think of is maybe there's some different options that Hubitat will respond to where the normal discovery it won't.

Do you have any ideas? Just hoping to figure out something to try

thanks,
joe

**Comment by loicortola** [comment]
Hello Joe,

sorry, I've been away from this repo for quite some time and shutdown notifications, didn't notice your message until today.
Have you resolved your issue since then?

Your issue is hard to address as I do not have any means to reproduce your issue.
Could you elaborate a little? Maybe more logging of the UPnP request / response threads?

**Comment by jpage4500** [comment]
Sorry, looking back at this I'm not sure what I expected you to do with something that's for a very specific device.

I think I was more looking to know if there would be any reason some devices weren't found using this library but were found using another app that does something similar (upnp browser - https://github.com/dgmltn/Android-UPnP-Browser/blob/master/app/src/main/java/com/dgmltn/upnpbrowser/UPnPDeviceFinder.java#L163)

It's been a while and I ended up looking at the source for both projects and implementing it in the app.. I would prefer using a library though so I don't have to maintain it.. I see there's some updates to this project so I'll try using it again to see if I can find the device I'm looking for. I can close this issue though since it's too vague!
