### ISSUE TITLE
No services are discovered on Windows

### ISSUE THREAD

**Issue by HeikoBornholdt** [resourcepool/ssdp-client#26]
The "Discover all SSDP services" example does not find any services under Windows.
The same code on the same network on the same computer finds services under macOS.

I checked the SSDP traffic with Wireshark and could not find any problems.
It looks like the MulticastSocket ignores the unicast "HTTP/1.1 200 OK" messages.

**Comment by KevinRoebert** [comment]
Same problem here. Under _Windows_, no services were found. 

If I test the same code on the same machine but under _elementary OS 5.1 Hera_ it finds services.

**Comment by loicortola** [comment]
Hello All!
Interesting issue.
I wonder how I could change it, has anyone tried a workaround?
I do not have a Windows setup around so it's hard to test.

I'd be happy to merge PRs on that topic.
@KevinRoebert? @heikobornholdt ?

**Comment by loicortola** [comment]
Closed due to inactivity

**Comment by smalldevcloud** [comment]
Same problem. Works on android, but not on Windows
