### ISSUE TITLE
Sometimes  application wants to handle multiple responses on its own

### ISSUE THREAD

**Issue by ntgr-xhan** [resourcepool/ssdp-client#32]
Sometimes an application wants to handle multiple responses on its own
However, it is not allowed here. For the same device, only the first response will be notified to the user-defined listener
```
if (!cache.containsKey(ssdpService.getSerialNumber())) {
      callback.onServiceDiscovered(ssdpService);
    }
    cache.put(ssdpService.getSerialNumber(), ssdpService);
```

**Comment by loicortola** [comment]
Thanks, PR reviewed

**Comment by loicortola** [comment]
Hi @hanxiao34 , waiting for a quick fix on your PR before merging and releasing
