### ISSUE TITLE
MulticastSocket should not specify port

### ISSUE THREAD

**Issue by bcingle** [resourcepool/ssdp-client#4]
SsdpClientImpl.java line 173 specifies 1900 as source port.  It should be dynamic port.  UDP packets returning to client are lost.  Removing the argument from the MulticastSocket constructor corrects the issue.

**Comment by loicortola** [comment]
Hello,
thanks for the issue. 
You are totally right. I couldn't see the issue because my host doesn't have a SSDP Server listening ;).

Releasing 2.1.0

**Comment by fruel** [comment]
The resolution for this issue breaks the "Discovery is not a mandatory activity. You might just want to listen to announcements" feature that is described in the README.

When no discovery request is sent the other hosts will send their announcements on port 1900 while this library is listening on a different, dynamic port.

I would suggest giving the user the option to choose which port should be used.
