### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by Albly** [resourcepool/ssdp-client#8]
It workes perfectly on every android device except my. (Android 5.1.1 LMY47V, MIUI Global 9.6.2.0 LAIMIFD)
I'm getting "java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)"
I tried to connect the phone to different Wi-Fi networks, disable firewall, but these did not solve the problem. 
After debuging the process i found that exception throws in https://github.com/resourcepool/ssdp-client/blob/master/src/main/java/io/resourcepool/ssdp/client/impl/SsdpClientImpl.java#L146
Can someone help me, please?

**Comment by loicortola** [comment]
Hello Alex...
Honestly without a device or the ability to reproduce, it would be hard for me to do anything...
What device is this? (Is this a stock android ROM or a specific one?)

**Comment by Albly** [comment]
The device is Xiaomi Redme 3. Yes , ROM is a stock

**Comment by loicortola** [comment]
Closed after inactivity
